[k3s-master]
w2l-srv-aap ansible_host=192.168.0.60 ansible_user=ls ansible_ssh_private_key_file=~/.ssh/raspberrypi ansible_ssh_common_args='-o IdentitiesOnly=yes'

[k3s-workers]
w2l-archpc-ls ansible_host=192.168.0.10 ansible_user=ls ansible_ssh_private_key_file=~/.ssh/private ansible_ssh_common_args='-o IdentitiesOnly=yes' ansible_port=2204
# w2l-archnb-ls ansible_host=192.168.0.11 ansible_user=ls

[k3s-all:children]
k3s-master
k3s-workers
