$ANSIBLE_VAULT;1.1;AES256
36643061373134363061353939303263303763383439623630323137343534623439666537626466
6464653661313737666433353665313139613534336636660a663034646565356633663663336265
34653538323831323533366264313230636335393264633135356561663262646136373535356234
6534376235326665620a623965386464626133346531616437653562366134353034653766623463
64646466336166373439616661363865376435363239656666326163363530616334
