---
- hosts: localhost
  connection: local

  tasks:

    - name: Create network
      community.docker.docker_network:
        name: wordpress

    - name: Create wordpress volume
      community.docker.docker_volume:
        name: wordpress

    - name: Create db volume
      community.docker.docker_volume:
        name: db

    - name: Deploy MySQL
      community.docker.docker_container:
        name: db
        image: mysql:8.0
        networks:
          - name: wordpress
        volumes:
          - db:/var/lib/mysql
        env:
          MYSQL_DATABASE: exampledb
          MYSQL_USER: exampleuser
          MYSQL_PASSWORD: examplepass
          MYSQL_RANDOM_ROOT_PASSWORD: "1"
        restart_policy: always

    - name: Wait 15 seconds for MySQL
      pause:
        seconds: 15

    - name: Deploy WordPress
      community.docker.docker_container:
        name: wordpress
        image: wordpress
        ports:
          - "8080:80"
        networks:
          - name: wordpress
        volumes:
          - wordpress:/var/www/html
        env:
          WORDPRESS_DB_HOST: db
          WORDPRESS_DB_USER: exampleuser
          WORDPRESS_DB_PASSWORD: examplepass
          WORDPRESS_DB_NAME: exampledb
        restart_policy: always
